### ISSUE TITLE
Catalog Visibility is set to visible by default

### ISSUE THREAD

**Issue by bryceadams** [woothemes/woocommerce-rest-api-docs#1]
When I create a product the catalog visibility is set to visible, not hidden (but docs say that it is hidden by default - I think it's better to be visible by default anyway).

http://woothemes.github.io/woocommerce-rest-api-docs/?shell#products-properties

@claudiosmweb

**Comment by claudiosmweb** [comment]
Create a product now with WC 2.3 using the API and show me how did you create and what returned.

**Comment by claudiosmweb** [comment]
I just saw that was not defined in the panel, but the return is hidden as speech in the documentation xD
I fix this in the core.

**Comment by bryceadams** [comment]
no you fix in docs

**Comment by bryceadams** [comment]
👳

**Comment by claudiosmweb** [comment]
@bryceadams fixed in the docs too now xD
