### ISSUE TITLE
Login Customer

### ISSUE THREAD

**Issue by cepages** [woothemes/woocommerce-rest-api-docs#12]
Hi I'm totally new in woocommerce, I'm trying to do an iOS app using this api. I think all fits except for the login for a customer.

What endpoint should I use if a customer would like to login with his user(or email) and password in the server to get all his details.

Thanks.

**Comment by claudiosmweb** [comment]
We don't have any endpoint for login and may we never will.

https://github.com/woothemes/woocommerce/pull/6133
