### ISSUE TITLE
Create Product

### ISSUE THREAD

**Issue by sasiano** [woothemes/woocommerce-rest-api-docs#14]
I want to create a product with oauth anf javascript (my website protocol is http).
I must use WooCommerce.post('products', data, function(err, data, res)...
but what is the library of "WooCommerce.post" to know this function?

**Comment by claudiosmweb** [comment]
Read the docs: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by sasiano** [comment]
please help me.
I read this doc several but not Helpful.
see my question in stackoverflow
http://stackoverflow.com/questions/31927610/create-product-with-woocommerce-api-and-oauth
Tank You!
