### ISSUE TITLE
Docs for 2.5

### ISSUE THREAD

**Issue by claudiosmweb** [woothemes/woocommerce-rest-api-docs#15]
- [x] [Support for product shipping classes](https://github.com/woothemes/woocommerce/pull/9118)
- [x] [Support to POST, PUT, and DELETE categories](https://github.com/woothemes/woocommerce/pull/9100)
- [x] [product/tags endpoints](https://github.com/woothemes/woocommerce/pull/9100)
- [x] Product attribute terms endpoints
- [x] [Filter products by tag, category, shipping classes or attributes](https://github.com/woothemes/woocommerce/issues/8971)
- [x] [Producs image properties alt and title writable](https://github.com/woothemes/woocommerce/pull/9136)
- [x] [Tax endpoint](https://github.com/woothemes/woocommerce/pull/9308)
- [x] `expand` filter for orders
- [x] [Product `menu_order`](https://github.com/woothemes/woocommerce/issues/9866)

**Comment by codingideas** [comment]
I am using the 2.5.0 beta 1 but how do I do this.

Say I have an attribute called apples which has an id of 1. So when I do this /wc-api/v3/products/attributes/1

I get this:

Array ( [has_archives] => [name] => Apples [order_by] => menu_order [slug] => pa_fruit [type] => select [id] => 1 )

Though I want to see the archive for Apples. So I get the list of name and ids for example Green, Red. How what endpoint will I do that?
