### ISSUE TITLE
UPDATE PRODUCT Method sets price and regular_price to 0.00 ( API v2 + API v3)

### ISSUE THREAD

**Issue by yatanasov** [woothemes/woocommerce-rest-api-docs#16]
GET
{
"product": {
"title": "Дамски боти в черно с връзки и заден цип",
"id": 47655,
"price": "199.00", - THE PRICE IS CORRECT
"regular_price": "199.00", - THE PRICE IS CORRECT
etc .....
etc ...........
}
}

"PUT" :
https://website.com/wc-api/v3/products/47655/?consumer_key=ck&consumer_secret=cs

DATA:

{
"product": {
"regular_price" : "106.00"
}
}

RESPONSE:
{
"product": {
"title": "Дамски боти в черно с връзки и заден цип",
"id": 47655,
"price": "0.00", ???????????? why is it 0 ?
"regular_price": "0.00", ?????????????? why is it 0 ?
etc .....
etc ...........
}
}

I also get frequent GATEWAY TIMEOUT error ........

Please advice or investigate as soon as possible.

Thanks for your efforts.

Best,
Yordan

**Comment by claudiosmweb** [comment]
Here is not a support channel...

> I also get frequent GATEWAY TIMEOUT error ........

Is your server saying it and not our API.

In your PUT data, you don't need to set the decimals, you can just send `"106"`.

**Comment by yatanasov** [comment]
Thank you, I am sorry for the mistake... : ( 

I am just really frustrated.. I tried to send data as you suggested but it made no difference. I will try to submit my request to the correct place. Thanks.
