### ISSUE TITLE
Create refund line_item data

### ISSUE THREAD

**Issue by danielhoey** [woothemes/woocommerce-rest-api-docs#17]
The data required to create a refund with line_items is not documented correctly. It suggests that the data should be line item properties, eg:

    {
      "order_refund": {
      ...
      "line_items": [{"id":1, "total": "10", ...}]
      }
    }

 but the data that the API expects is:

    {
      "order_refund": {
      ...
      "line_items": {1: {"refund_total": "10", "refund_tax": "0", "qty": 1}]
      }
    }

(http://woothemes.github.io/woocommerce-rest-api-docs/#create-a-refund-for-an-order)

**Comment by claudiosmweb** [comment]
@danielhoey not really, we make reference for `line_items` in this case products.
