### ISSUE TITLE
Attributes Properties: options - description improvement

### ISSUE THREAD

**Issue by pawelkmpt** [woothemes/woocommerce-rest-api-docs#18]
I'd like to propose improvement for Attributes Properties section. When updating product, `options` attribute can be either string or array: https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-api-products.php#L1283

Attributes:
* **passed in array** should be slugs (otherwise eg. `11.11.2015` becomes `11-11-2015`),
* **passed as string** should be separated with `|`.

Thanks!

**Comment by claudiosmweb** [comment]
Seems to be reported on the wrong place.
If you want to change something in the API need report in https://github.com/woothemes/woocommerce
