### ISSUE TITLE
Download links in product variations are visible

### ISSUE THREAD

**Issue by benwwalker** [woothemes/woocommerce-rest-api-docs#190]
Hi,

I have a couple of products with physical/downloadable variations, and the files are hosted externally (onedrive, dropbox etc). 

How should I list the variations and their prices, without retrieving the direct download link?

For example, my shop lists a book. The book has two variations, a physical one and a virtual (downloadable) one. The download link is off-site since it's a huge book, and I'd rather use another server's bandwidth.

I need to make a request to ```https://www.myamazingbookshop.com/wp-json/wc/v3/products/{my_book_id}/variations``` from my product page, so I can populate a dropdown select box on with something like variation and price, and there in the REST response is

```json
{
   "id": 1,
   "name": "My Amazing Book",
   "price": "10",
   "virtual": true,
   "downloadable": true,
   "downloads": [
   {
      "id": "blah",
      "name": "MY AMAZING BOOK",
       "file": "https://www.dropbox.com/s/my_download_link_that_bypasses_everything.pdf"
   }
   ]
}
```

So anyone nosing around in devtools can see the response and download the file without having to go through the cart process at all?

What's the right way to do this? 
Make my own API that does a SSR?
Stop worrying about it?
Wish for a GraphQL endpoint so we can do away with all the extra REST fluff?

**Comment by rrennick** [comment]
> So anyone nosing around in devtools can see the response and download the file without having to go through the cart process at all?

@benwwalker The WC rest api is not publicly accessible. You need api keys to access the api.

**Comment by benwwalker** [comment]
> @benwwalker The WC rest api is not publicly accessible. You need api keys to access the api.

I see that bit - I think the issue isn't about accessing the the api, it's that the "file" attribute is visible for variations? 

I can see the json response in a devtools network tab. Whilst this doesn't seem to be an issue with woocommerce/wordpress hosted files (the url is changed and you get a 403 if you try to access them) off-site downloads are just a redirect. 

So let's say I was hosting a file > 512mb elsewhere and wanted to sell it. WooCommerce lets me add the download link as  https://bigfiles.com/my_big_file.zip. Unfortunately, that download link is then available there in the devtools window, without any purchase necessary.. I get that there is some degree of risk - anyone with a link to my_big_file.zip can download it anyway - but it would be nice if there was a way to turn off the download details in the variation/product API.

**Comment by rrennick** [comment]
@benwwalker Can you describe the steps you are taking to where you can see the link from an anonymous browser?

**Comment by benwwalker** [comment]
@rrennick sure - 

My site is built in React and has some swr/axios loading going on to populate a shop page with a list of products. 

The shop is at www.myamazingbookshop.com/shop, whilst the cms/woocommerce site of things is at https://wp.myamazingbookshop.com/wp-json/wc/v3/products

The page loads, it triggers axios to get the products from woocommerce and if I look in devtools I can see the network request and response.

I then and visit a product page. Say, www.myamazingbookshop.com/shop/{book_id} - This needs to load variations for the book, since they're at different prices. 

Again, more swr/axios - https://wp.myamazingbookshop.com/wp-json/wc/v3/products/{my_book_id}/variations

In devtools' network tab, I can see the request heading off and the response come back as a long string. If I format the string, I get the JSON.

One of the properties of a variation response is "downloads", and one of the attributes in a "download" is "file" - which is a link to the downloadable file. If that file is within the Wordpress/WooCommerce ecosystem, the link doesn't work - this is correct since presumably WooCommerce deals with the authentication for it. If (however) the link is outside the ecosystem - dropbox etc - then the link is in plain text. Visit the plain text link, and suddenly I can download the file with no purchase needed.

You can try it yourself. Just make a product with a downloadable variant, put any old cloud-hosted link as the file, then create a page that fetches product variants. You'll see that the downloads/file gets populated with the cloud link.

**Comment by rrennick** [comment]
> then create a page that fetches product variants.

Your react app must be authorizing and reading from the API. The downloads are part of our published specifications for authorized read/write. For your application, you will need to make your own route/endpoint that only includes data that is publicly accessible from the front end of a site.

**Comment by claudiosanches** [comment]
Hello @benwwalker,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
