### ISSUE TITLE
Search/Retrieve customer via first_name, last_name billing_phone

### ISSUE THREAD

**Issue by dkalantzis** [woothemes/woocommerce-rest-api-docs#194]
Anyone that has any idea how and if that is currently possible?

**Comment by claudiosanches** [comment]
Hello @dkalantzis,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
