### ISSUE TITLE
Retreive order id where one cupons was used

### ISSUE THREAD

**Issue by RASTecnoTI** [woothemes/woocommerce-rest-api-docs#195]
Hi
I need to now if is possible I get the order id where the coupon was used. I have on specifique product where I use the coupons and I need to know the order generated when the coupon is used.
Thank you

**Comment by claudiosanches** [comment]
Hello @RASTecnoTI,

For support about the WooCommerce REST API please use our public forum in WordPress.org: https://wordpress.org/support/plugin/woocommerce/

I'm closing since this repository is to manage and keep the REST API documentation only.
Thanks.
