### ISSUE TITLE
Creating categories and tags using the woocommerce REST api issue(V3)

### ISSUE THREAD

**Issue by harunthuo** [woothemes/woocommerce-rest-api-docs#20]
Looks like the new V3 does not allow creating of product categories and tags when creating a product using the api:

   print_r( $client->products->create( array( 'title' => 'product_name','sku' => 'sku_value', 'type' => 'simple', 'regular_price' => '1000', 'short_description'=>'short description', 'categories' => Array ('category1','category2','category3' ), 'tags'=> array('product_tag'))));

all the other properties are still created but not categories and tags. returns an empty array:

["categories"]=>
    array(0) {
    }
["tags"]=>
   array(0) {
    }

so question is: how are categories and tags created using the REST api V3?

**Comment by claudiosmweb** [comment]
This will be possible in version 3.1

**Comment by claudiosmweb** [comment]
You need to send categories and tags IDs.
In version 3.1 we have available endpoints to create categories and tags.

**Comment by harunthuo** [comment]
thanks for getting back. 

that is great to hear. when are you releasing version 3.1?

**Comment by claudiosmweb** [comment]
Within WooCommerce 2.5.
We not yet have a release date, but it will be this year.

**Comment by harunthuo** [comment]
cool. thanks
