### ISSUE TITLE
Misguiding PHP example for sending REST API requests

### ISSUE THREAD

**Issue by xxxdepy** [woothemes/woocommerce-rest-api-docs#200]
Under the PHP examples the latest doc uses  `$woocommerce->post/get/put` etc method which doesn't even exist. 

```
<?php
print_r($woocommerce->get('data/currencies/current'));
?>
```

**Comment by claudiosanches** [comment]
Hello @xxxdepy

Those exists if you install our PHP library as indicated in our documentation: https://woocommerce.github.io/woocommerce-rest-api-docs/?php#libraries-and-tools
