### ISSUE TITLE
Please update documentation about v4

### ISSUE THREAD

**Issue by flexjoly** [woothemes/woocommerce-rest-api-docs#205]
Hi,

We are using this plugin to integrate with a supplier. I don't have much experience with woocommerce, so we only follow the api documentation. 
There is no indication that v3 is deprecated. 😞 
Can you please add a link to the new version and docu?

Thanks in advance
flexJoly

**Comment by rrennick** [comment]
> There is no indication that v3 is deprecated.

v3 isn't deprecated. v4 is in early development.
