### ISSUE TITLE
PUT /wp-json/wc/v3/products/<id> change to POST /wp-json/wc/v3/products/<id>

### ISSUE THREAD

**Issue by diegogazzolo** [woothemes/woocommerce-rest-api-docs#232]
Aparently now we must use POST instead of PUT when updating products.

**Comment by rrennick** [comment]
@diegogazzolo This repo is for the scripts that generate the documentation vs being the repository that has the documentation. 

However, to respond to your statement- we have not made any HTTP METHOD changes to the REST API. You may want to check your web server configuration to see whether it supports `PUT` requests.
