### ISSUE TITLE
Documentation for product properties incomplete

### ISSUE THREAD

**Issue by ad-on-is** [woothemes/woocommerce-rest-api-docs#30]
In the file class-wc-api-products.php there's this code at line 330
```php
// Product name (slug).
if ( isset( $data['name'] ) ) {
	wp_update_post( array( 'ID' => $id, 'post_name' => sanitize_title( $data['name'] ) ) );
}
```

It's nowhere in the official documentation that 'name' is a property for a product and that it can be used to set the post_name, that's responsible for the product's url.

IMHO it's definitely worth mentioning in the docs, since modifying the post_name is an urgent feature, and I accidentally found it in the code.

btw. maybe it should also be implemented in the product create function

**Comment by claudiosmweb** [comment]
Closed 5 hours ago https://github.com/woothemes/woocommerce-rest-api-docs/commit/34863d9d9a5e1b57adf602b8067550d252151628 ;)

**Comment by claudiosmweb** [comment]
> btw. maybe it should also be implemented in the product create function

I'll add it into a future version.

**Comment by ad-on-is** [comment]
*thumbsup*
