### ISSUE TITLE
Index - Meta properties - 'thousand_separator' description is incorrect

### ISSUE THREAD

**Issue by osrecki** [woothemes/woocommerce-rest-api-docs#31]
On the API Index page there is the `Meta Properties` section which contains the table with attributes' descriptions.

Description for the `thousand_separator` attribute says:
> The unit set for product weights. Valid units are `kg`, `g`, `lbs`, `oz`

Instead, it should say something like:
> Thousands separator, e.g `.`

**Comment by claudiosmweb** [comment]
@osrecki thanks :)
