### ISSUE TITLE
wp-api/v1: _links

### ISSUE THREAD

**Issue by kongper** [woothemes/woocommerce-rest-api-docs#38]
Product properties: '_links' not part of documentation. Should be?

**Comment by claudiosmweb** [comment]
It's not part of the parameters, you should expect have `_links` in all endpoints in the WP REST API.
WP REST API v2 docs don't have any documentation for it too: http://v2.wp-api.org/reference/posts/

**Comment by kongper** [comment]
Of course. My bad.
