### ISSUE TITLE
Customers endpoint seems broken

### ISSUE THREAD

**Issue by Lewiscowles1986** [woothemes/woocommerce-rest-api-docs#43]
So when searching for a customer by e-mail I noticed the WooCommerce docs seem broken

` /wp-json/wc/v1/customers` returns a wordpress 404

`/wc-api/v3/customers` works, however appending `?email=ABC@XYZ.COM` or `?filter[email]=ABC@XYZ.COM` returns all customers, which seems undesirable and contrary to the documentation https://woothemes.github.io/woocommerce-rest-api-docs/?shell#list-all-customers

WooCommerce 2.6.2, WordPress 4.5.3

**Comment by Lewiscowles1986** [comment]
looks like `/wc-api/v3/customers/email/ABC@XYZ.COM` works, which is so strange, it's not even like the other API end-points

this https://woothemes.github.io/woocommerce-rest-api-docs/?shell#retrieve-a-customer led me to attempt throwing more random strings into the API

**Comment by claudiosmweb** [comment]
Looks like you reading the docs for our integration with WP REST API and trying with or legacy API v3.

Here the docs for the legacy v3: https://woothemes.github.io/woocommerce-rest-api-docs/v3.html
