### ISSUE TITLE
is there any API for add To cart

### ISSUE THREAD

**Issue by vjijardar** [woothemes/woocommerce-rest-api-docs#49]
I couldn't  find any API for Add to cart in Latest API version v1 & any API Version.

**Comment by claudiosmweb** [comment]
Because don't have and don't need any.
You can use the order endpoint for it.

**Comment by FabioMarcone** [comment]
Hi Claudio,
using order endpoint, after adding a new order (from a distinct web app) is it possibile to redirect user to this new order (cart?) page to complete checkout and payment? how?

Thanks in advance,
Fabio

**Comment by dhakshinait** [comment]
@FabioMarcone , Did you find solution for it?. If it is so, can you tell me how you have created 'Add to cart' feature using API?. thanks in advance.
