### ISSUE TITLE
meta_data documentation missing for orders

### ISSUE THREAD

**Issue by neonics** [woothemes/woocommerce-rest-api-docs#51]
The (very useful) `meta_data` attribute documentation is missing for [create order](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L554) and [update order](https://github.com/woothemes/woocommerce/blob/master/includes/api/class-wc-rest-orders-controller.php#L1055) in the [_orders.md](https://github.com/woothemes/woocommerce-rest-api-docs/blob/master/source/includes/wp-api-v1/_orders.md) file. (WooCommerce 2.6.4, wp-json/wc/v1).

(Also, being able to retrieve this would be nice).

**Comment by claudiosmweb** [comment]
Better keep this for now, since this has been improved for 2.7.
