### ISSUE TITLE
Oauth Spec Note

### ISSUE THREAD

**Issue by sparkweb** [woothemes/woocommerce-rest-api-docs#8]
In the Oauth Tips section, the docs say:

`Some OAuth libraries add an ampersand to the provided secret key before generating the signature. This does not adhere to the OAuth spec and the ampersand should be removed prior to generating the signature.`

I think this is incorrect, though, given the spec at http://oauth.net/core/1.0a/#anchor15:

`The HMAC-SHA1 signature method uses the HMAC-SHA1 signature algorithm as defined in RFC2104 where the Signature Base String is the text and the key is the concatenated values (each first encoded per Parameter Encoding) of the Consumer Secret and Token Secret, separated by an '&' character (ASCII code 38) even if empty.`

Since Token Secret isn't used by WooCommerce I believe that the standard indicates that the & should be there anyway. So shouldn't the docs indicate that this is _against_ spec? The Guzzle library I was using uses an & in the middle even if empty and had to be patched to make it work against the WooCommerce API.

**Comment by maxrice** [comment]
Yep, you're correct here -- the docs should be updated to reflect that the spec isn't followed exactly, see my comment [here](https://github.com/woothemes/woocommerce/issues/7928#issuecomment-91632734) :smile:

**Comment by claudiosmweb** [comment]
Thanks for the Pull Request :)
